// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnPhone(arg1, arg2) {
  return window['go']['main']['App']['ConnPhone'](arg1, arg2);
}

export function InstallApk() {
  return window['go']['main']['App']['InstallApk']();
}

export function Msg(arg1, arg2) {
  return window['go']['main']['App']['Msg'](arg1, arg2);
}

export function UnInstallApk() {
  return window['go']['main']['App']['UnInstallApk']();
}
