// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnPhone(arg1:boolean,arg2:boolean):Promise<Error>;

export function InstallApk():Promise<Error>;

export function Msg(arg1:string,arg2:string):Promise<string>;

export function UnInstallApk():Promise<Error>;
